platform :ios, '11.0'
use_frameworks!

target 'TopRepoIOS' do
 pod 'lottie-ios'
 pod 'Swinject'
 pod 'Alamofire'
 pod 'RxSwift', '6.7.0'
 pod 'RxCocoa', '6.7.0'  
 pod "SwiftyMocky"
end

target 'TopRepoIOSUITests' do
  pod 'lottie-ios'
  pod 'Swinject'
  pod 'Alamofire'
  pod 'RxSwift', '6.7.0'
  pod 'RxCocoa', '6.7.0'
end
